// <auto-generated />
namespace ProtPracticeMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class version04 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version04));
        
        string IMigrationMetadata.Id
        {
            get { return "201912060927271_version04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
