// <auto-generated />
namespace UniversityProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class to_RDFOX_local : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(to_RDFOX_local));
        
        string IMigrationMetadata.Id
        {
            get { return "201912091321363_to_RDFOX_local"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
